name: Richpear Secure Tunnel
version: "0.2.7"
slug: richpear_secure_tunnel
description: Secure outbound tunnel registration and connection for Home Assistant.
startup: services
boot: auto
init: false
host_network: true
privileged: []
ports: {}
ingress: true
ingress_port: 8099
panel_icon: mdi:cloud-lock
panel_title: Richpear Tunnel
arch:
  - amd64
  - aarch64
  - armv7
options:
  control_plane_url: "https://admin.cz.richpear.cz"
  email: ""
  subdomain: ""
  device_name: "home-assistant"
  ha_port: 8123
  upstream_host_header: "localhost"
schema:
  control_plane_url: url
  email: "str?"
  subdomain: "str?"
  device_name: str
  ha_port: port
  upstream_host_header: str
